import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import Sidebar from "./components/SideBar";
import ReduxProvider from "@/redux/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <a href="#main-content" className="skip-link sr-only focus:not-sr-only">
          Skip to main content
        </a>
        <ReduxProvider>
          <div className="mx-auto max-w-[1440px] md:flex">
            <Sidebar />
            <main
              id="main-content"
              className="overflow-hidden pt-[65px] md:grow md:pt-0"
              tabIndex={-1}
            >
              {children}
            </main>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
